### PR TITLE
Change gradle publish plugin

### PR DESCRIPTION
**Pull request by leungkinghin**
#### Summary 
[gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/) is being used for central maven publish but it is no longer supported. It is recommended to use [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin) instead

#### Hints for Review
- `build.gradle` has been modified to use another plugin.
- `nexus-staging.gradle` has been deprecated. Instead `nexus-publish.gradle` with different configuration structure has been adapted.
- New gradle tasks have to be executed since old plugin has been replaced.
- Repositories config in `maven-publish.gradle` is no longer applicable since it is only for old plugin.

### CODE REVIEW

**Review by lojzatran — APPROVED** [review]

**Comment by lojzatran** [comment]
Did you test the process?

**Comment by leungkinghin** [comment]
> Did you test the process?

Yes. I did the test in another branch. 
https://github.com/commercetools/commercetools-sync-java/tree/change-gradle-nexus-plugin-dummy

ci.yml is modified in this dummy branch so that artifact is pushed to sonatype staging repo and closed succesfully.

**Review by praveenkumarct — COMMENTED** [review]
If you have already tested, changes looks good for me.
Could you please check [/cd.yml](https://github.com/commercetools/commercetools-sync-java/blob/44067a2d61f2de77408924fcb924b445f03ee60d/.github/workflows/cd.yml#L75).
It still says check for Step 3. But I couldn't find any such step in Build doc.
> check <https://github.com/commercetools/commercetools-sync-java/blob/master/docs/BUILD.md#step-3-publish-to-maven-central|here> for the next steps

**Comment by leungkinghin** [comment]
> If you have already tested, changes looks good for me.
> Could you please check [/cd.yml](https://github.com/commercetools/commercetools-sync-java/blob/44067a2d61f2de77408924fcb924b445f03ee60d/.github/workflows/cd.yml#L75).
> It still says check for Step 3. But I couldn't find any such step in Build doc.
> 
> > check [https://github.com/commercetools/commercetools-sync-java/blob/master/docs/BUILD.md#step-3-publish-to-maven-central|here](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/BUILD.md#step-3-publish-to-maven-central%7Chere) for the next steps

Good catch!
I have modified the slack message
https://github.com/commercetools/commercetools-sync-java/pull/732/commits/2425cb37b6698a8283451e42f94943bf5e2875d9

**Review by praveenkumarct — APPROVED** [review]

**Pull request merged**
